// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: calculator.capnp

#include "calculator.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<75> b_f3488032057d7c3f = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     63, 124, 125,   5,  50, 128,  72, 243,
     25,   0,   0,   0,   3,   0,   0,   0,
    163, 230, 247, 200, 181, 215, 165, 212,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    178,   0,   0,   0, 166,   2,   0,   0,
     21,   0,   0,   0,  34,   1,   0,   0,
     37,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  71,   1,   0,   0,
    249,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     20,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     48, 213, 197,   6,  24, 188, 129, 250,
     70,  76, 167, 187, 112,   6, 159, 183,
    145,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    133,   0,   0,   0,   7,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   4, 128, 154, 199,  78, 127, 153,
     43,  13, 247, 233, 182,  22,  16, 243,
    121,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    113,   0,   0,   0,   7,   0,   0,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
     91, 167, 140, 164, 211, 175, 229, 220,
    165, 200, 151, 172,  25,   0,  17, 220,
    101,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     93,   0,   0,   0,   7,   0,   0,   0,
      3,   0,   0,   0,   0,   0,   0,   0,
    151,  57,  15,   7,  26,  87, 102, 129,
    209,  23, 159, 145,  39, 134,  38, 184,
     81,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,   7,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
    238, 164, 128, 116,   0,  91,  17, 191,
    154, 116,  54, 113,  41,  29,  48, 248,
     57,   0,   0,   0, 138,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     53,   0,   0,   0,   7,   0,   0,   0,
     97, 100, 100,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    115, 117,  98, 116, 114,  97,  99, 116,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    109, 117, 108, 116, 105, 112, 108, 121,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    100, 105, 118, 105, 100, 101,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    103, 101, 116,  83, 117,  98,  67,  97,
    108,  99, 117, 108,  97, 116, 111, 114,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_f3488032057d7c3f = b_f3488032057d7c3f.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_f3488032057d7c3f[] = {
  &s_8166571a070f3997,
  &s_997f4ec79a800400,
  &s_b79f0670bba74c46,
  &s_b8268627919f17d1,
  &s_bf115b007480a4ee,
  &s_dc110019ac97c8a5,
  &s_dce5afd3a48ca75b,
  &s_f31016b6e9f70d2b,
  &s_f8301d297136749a,
  &s_fa81bc1806c5d530,
};
static const uint16_t m_f3488032057d7c3f[] = {0, 3, 4, 2, 1};
const ::capnp::_::RawSchema s_f3488032057d7c3f = {
  0xf3488032057d7c3f, b_f3488032057d7c3f.words, 75, d_f3488032057d7c3f, m_f3488032057d7c3f,
  10, 5, nullptr, nullptr, nullptr, { &s_f3488032057d7c3f, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<50> b_fa81bc1806c5d530 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     48, 213, 197,   6,  24, 188, 129, 250,
     36,   0,   0,   0,   1,   0,   2,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 122,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46,  97, 100, 100,  36,
     80,  97, 114,  97, 109, 115,   0,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
    108, 101, 102, 116,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 105, 103, 104, 116,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_fa81bc1806c5d530 = b_fa81bc1806c5d530.words;
#if !CAPNP_LITE
static const uint16_t m_fa81bc1806c5d530[] = {0, 1};
static const uint16_t i_fa81bc1806c5d530[] = {0, 1};
const ::capnp::_::RawSchema s_fa81bc1806c5d530 = {
  0xfa81bc1806c5d530, b_fa81bc1806c5d530.words, 50, nullptr, m_fa81bc1806c5d530,
  0, 2, i_fa81bc1806c5d530, nullptr, nullptr, { &s_fa81bc1806c5d530, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<35> b_b79f0670bba74c46 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     70,  76, 167, 187, 112,   6, 159, 183,
     36,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 130,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46,  97, 100, 100,  36,
     82, 101, 115, 117, 108, 116, 115,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    118,  97, 108, 117, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_b79f0670bba74c46 = b_b79f0670bba74c46.words;
#if !CAPNP_LITE
static const uint16_t m_b79f0670bba74c46[] = {0};
static const uint16_t i_b79f0670bba74c46[] = {0};
const ::capnp::_::RawSchema s_b79f0670bba74c46 = {
  0xb79f0670bba74c46, b_b79f0670bba74c46.words, 35, nullptr, m_b79f0670bba74c46,
  0, 1, i_b79f0670bba74c46, nullptr, nullptr, { &s_b79f0670bba74c46, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<51> b_997f4ec79a800400 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
      0,   4, 128, 154, 199,  78, 127, 153,
     36,   0,   0,   0,   1,   0,   2,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 162,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 115, 117,  98, 116,
    114,  97,  99, 116,  36,  80,  97, 114,
     97, 109, 115,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
    108, 101, 102, 116,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 105, 103, 104, 116,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_997f4ec79a800400 = b_997f4ec79a800400.words;
#if !CAPNP_LITE
static const uint16_t m_997f4ec79a800400[] = {0, 1};
static const uint16_t i_997f4ec79a800400[] = {0, 1};
const ::capnp::_::RawSchema s_997f4ec79a800400 = {
  0x997f4ec79a800400, b_997f4ec79a800400.words, 51, nullptr, m_997f4ec79a800400,
  0, 2, i_997f4ec79a800400, nullptr, nullptr, { &s_997f4ec79a800400, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<36> b_f31016b6e9f70d2b = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     43,  13, 247, 233, 182,  22,  16, 243,
     36,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 170,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 115, 117,  98, 116,
    114,  97,  99, 116,  36,  82, 101, 115,
    117, 108, 116, 115,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    118,  97, 108, 117, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_f31016b6e9f70d2b = b_f31016b6e9f70d2b.words;
#if !CAPNP_LITE
static const uint16_t m_f31016b6e9f70d2b[] = {0};
static const uint16_t i_f31016b6e9f70d2b[] = {0};
const ::capnp::_::RawSchema s_f31016b6e9f70d2b = {
  0xf31016b6e9f70d2b, b_f31016b6e9f70d2b.words, 36, nullptr, m_f31016b6e9f70d2b,
  0, 1, i_f31016b6e9f70d2b, nullptr, nullptr, { &s_f31016b6e9f70d2b, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<51> b_dce5afd3a48ca75b = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     91, 167, 140, 164, 211, 175, 229, 220,
     36,   0,   0,   0,   1,   0,   2,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 162,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 109, 117, 108, 116,
    105, 112, 108, 121,  36,  80,  97, 114,
     97, 109, 115,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
    108, 101, 102, 116,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 105, 103, 104, 116,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_dce5afd3a48ca75b = b_dce5afd3a48ca75b.words;
#if !CAPNP_LITE
static const uint16_t m_dce5afd3a48ca75b[] = {0, 1};
static const uint16_t i_dce5afd3a48ca75b[] = {0, 1};
const ::capnp::_::RawSchema s_dce5afd3a48ca75b = {
  0xdce5afd3a48ca75b, b_dce5afd3a48ca75b.words, 51, nullptr, m_dce5afd3a48ca75b,
  0, 2, i_dce5afd3a48ca75b, nullptr, nullptr, { &s_dce5afd3a48ca75b, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<36> b_dc110019ac97c8a5 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    165, 200, 151, 172,  25,   0,  17, 220,
     36,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 170,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 109, 117, 108, 116,
    105, 112, 108, 121,  36,  82, 101, 115,
    117, 108, 116, 115,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    118,  97, 108, 117, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_dc110019ac97c8a5 = b_dc110019ac97c8a5.words;
#if !CAPNP_LITE
static const uint16_t m_dc110019ac97c8a5[] = {0};
static const uint16_t i_dc110019ac97c8a5[] = {0};
const ::capnp::_::RawSchema s_dc110019ac97c8a5 = {
  0xdc110019ac97c8a5, b_dc110019ac97c8a5.words, 36, nullptr, m_dc110019ac97c8a5,
  0, 1, i_dc110019ac97c8a5, nullptr, nullptr, { &s_dc110019ac97c8a5, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<51> b_8166571a070f3997 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    151,  57,  15,   7,  26,  87, 102, 129,
     36,   0,   0,   0,   1,   0,   2,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 146,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 100, 105, 118, 105,
    100, 101,  36,  80,  97, 114,  97, 109,
    115,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
    108, 101, 102, 116,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 105, 103, 104, 116,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_8166571a070f3997 = b_8166571a070f3997.words;
#if !CAPNP_LITE
static const uint16_t m_8166571a070f3997[] = {0, 1};
static const uint16_t i_8166571a070f3997[] = {0, 1};
const ::capnp::_::RawSchema s_8166571a070f3997 = {
  0x8166571a070f3997, b_8166571a070f3997.words, 51, nullptr, m_8166571a070f3997,
  0, 2, i_8166571a070f3997, nullptr, nullptr, { &s_8166571a070f3997, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<36> b_b8268627919f17d1 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    209,  23, 159, 145,  39, 134,  38, 184,
     36,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 154,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 100, 105, 118, 105,
    100, 101,  36,  82, 101, 115, 117, 108,
    116, 115,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    118,  97, 108, 117, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_b8268627919f17d1 = b_b8268627919f17d1.words;
#if !CAPNP_LITE
static const uint16_t m_b8268627919f17d1[] = {0};
static const uint16_t i_b8268627919f17d1[] = {0};
const ::capnp::_::RawSchema s_b8268627919f17d1 = {
  0xb8268627919f17d1, b_b8268627919f17d1.words, 36, nullptr, m_b8268627919f17d1,
  0, 1, i_b8268627919f17d1, nullptr, nullptr, { &s_b8268627919f17d1, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<21> b_bf115b007480a4ee = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    238, 164, 128, 116,   0,  91,  17, 191,
     36,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 226,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 103, 101, 116,  83,
    117,  98,  67,  97, 108,  99, 117, 108,
     97, 116, 111, 114,  36,  80,  97, 114,
     97, 109, 115,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_bf115b007480a4ee = b_bf115b007480a4ee.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_bf115b007480a4ee = {
  0xbf115b007480a4ee, b_bf115b007480a4ee.words, 21, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_bf115b007480a4ee, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<38> b_f8301d297136749a = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    154, 116,  54, 113,  41,  29,  48, 248,
     36,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 234,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  46, 103, 101, 116,  83,
    117,  98,  67,  97, 108,  99, 117, 108,
     97, 116, 111, 114,  36,  82, 101, 115,
    117, 108, 116, 115,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     24,   0,   0,   0,   2,   0,   1,   0,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0,   0,   0,   0,   0,
     63, 124, 125,   5,  50, 128,  72, 243,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_f8301d297136749a = b_f8301d297136749a.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_f8301d297136749a[] = {
  &s_f3488032057d7c3f,
};
static const uint16_t m_f8301d297136749a[] = {0};
static const uint16_t i_f8301d297136749a[] = {0};
const ::capnp::_::RawSchema s_f8301d297136749a = {
  0xf8301d297136749a, b_f8301d297136749a.words, 38, d_f8301d297136749a, m_f8301d297136749a,
  1, 1, i_f8301d297136749a, nullptr, nullptr, { &s_f8301d297136749a, nullptr, nullptr, 0, 0, nullptr }, true
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<50> b_b31d74267b640652 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     82,   6, 100, 123,  38, 116,  29, 179,
     25,   0,   0,   0,   1,   0,   2,   0,
    163, 230, 247, 200, 181, 215, 165, 212,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    231,   2,   0,   0,  36,   3,   0,   0,
     21,   0,   0,   0,  26,   1,   0,   0,
     37,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  65, 100, 100,  80,  97, 114,  97,
    109, 115,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
    108, 101, 102, 116,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 105, 103, 104, 116,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_b31d74267b640652 = b_b31d74267b640652.words;
#if !CAPNP_LITE
static const uint16_t m_b31d74267b640652[] = {0, 1};
static const uint16_t i_b31d74267b640652[] = {0, 1};
const ::capnp::_::RawSchema s_b31d74267b640652 = {
  0xb31d74267b640652, b_b31d74267b640652.words, 50, nullptr, m_b31d74267b640652,
  0, 2, i_b31d74267b640652, nullptr, nullptr, { &s_b31d74267b640652, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<36> b_a9631c61e9f16be9 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    233, 107, 241, 233,  97,  28,  99, 169,
     25,   0,   0,   0,   1,   0,   1,   0,
    163, 230, 247, 200, 181, 215, 165, 212,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     38,   3,   0,   0,  86,   3,   0,   0,
     21,   0,   0,   0,  82,   1,   0,   0,
     41,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101, 120,  97, 109, 112, 108, 101,  47,
     99,  97, 108,  99, 117, 108,  97, 116,
    111, 114,  46,  99,  97, 112, 110, 112,
     58,  67,  97, 108,  99, 117, 108,  97,
    116, 111, 114,  82, 101, 115, 117, 108,
    116,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    118,  97, 108, 117, 101,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     11,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_a9631c61e9f16be9 = b_a9631c61e9f16be9.words;
#if !CAPNP_LITE
static const uint16_t m_a9631c61e9f16be9[] = {0};
static const uint16_t i_a9631c61e9f16be9[] = {0};
const ::capnp::_::RawSchema s_a9631c61e9f16be9 = {
  0xa9631c61e9f16be9, b_a9631c61e9f16be9.words, 36, nullptr, m_a9631c61e9f16be9,
  0, 1, i_a9631c61e9f16be9, nullptr, nullptr, { &s_a9631c61e9f16be9, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


#if !CAPNP_LITE
::capnp::Request< ::Calculator::AddParams,  ::Calculator::AddResults>
Calculator::Client::addRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Calculator::AddParams,  ::Calculator::AddResults>(
      0xf3488032057d7c3full, 0, sizeHint, {true});
}
::kj::Promise<void> Calculator::Server::add(AddContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "example/calculator.capnp:Calculator", "add",
      0xf3488032057d7c3full, 0);
}
::capnp::Request< ::Calculator::SubtractParams,  ::Calculator::SubtractResults>
Calculator::Client::subtractRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Calculator::SubtractParams,  ::Calculator::SubtractResults>(
      0xf3488032057d7c3full, 1, sizeHint, {true});
}
::kj::Promise<void> Calculator::Server::subtract(SubtractContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "example/calculator.capnp:Calculator", "subtract",
      0xf3488032057d7c3full, 1);
}
::capnp::Request< ::Calculator::MultiplyParams,  ::Calculator::MultiplyResults>
Calculator::Client::multiplyRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Calculator::MultiplyParams,  ::Calculator::MultiplyResults>(
      0xf3488032057d7c3full, 2, sizeHint, {true});
}
::kj::Promise<void> Calculator::Server::multiply(MultiplyContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "example/calculator.capnp:Calculator", "multiply",
      0xf3488032057d7c3full, 2);
}
::capnp::Request< ::Calculator::DivideParams,  ::Calculator::DivideResults>
Calculator::Client::divideRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Calculator::DivideParams,  ::Calculator::DivideResults>(
      0xf3488032057d7c3full, 3, sizeHint, {true});
}
::kj::Promise<void> Calculator::Server::divide(DivideContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "example/calculator.capnp:Calculator", "divide",
      0xf3488032057d7c3full, 3);
}
::capnp::Request< ::Calculator::GetSubCalculatorParams,  ::Calculator::GetSubCalculatorResults>
Calculator::Client::getSubCalculatorRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Calculator::GetSubCalculatorParams,  ::Calculator::GetSubCalculatorResults>(
      0xf3488032057d7c3full, 4, sizeHint, {false});
}
::kj::Promise<void> Calculator::Server::getSubCalculator(GetSubCalculatorContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "example/calculator.capnp:Calculator", "getSubCalculator",
      0xf3488032057d7c3full, 4);
}
::capnp::Capability::Server::DispatchCallResult Calculator::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xf3488032057d7c3full:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("example/calculator.capnp:Calculator", interfaceId);
  }
}
::capnp::Capability::Server::DispatchCallResult Calculator::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        add(::capnp::Capability::Server::internalGetTypedContext<
             ::Calculator::AddParams,  ::Calculator::AddResults>(context)),
        false,
        false
      };
    case 1:
      return {
        subtract(::capnp::Capability::Server::internalGetTypedContext<
             ::Calculator::SubtractParams,  ::Calculator::SubtractResults>(context)),
        false,
        false
      };
    case 2:
      return {
        multiply(::capnp::Capability::Server::internalGetTypedContext<
             ::Calculator::MultiplyParams,  ::Calculator::MultiplyResults>(context)),
        false,
        false
      };
    case 3:
      return {
        divide(::capnp::Capability::Server::internalGetTypedContext<
             ::Calculator::DivideParams,  ::Calculator::DivideResults>(context)),
        false,
        false
      };
    case 4:
      return {
        getSubCalculator(::capnp::Capability::Server::internalGetTypedContext<
             ::Calculator::GetSubCalculatorParams,  ::Calculator::GetSubCalculatorResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "example/calculator.capnp:Calculator",
          0xf3488032057d7c3full, methodId);
  }
}
#endif  // !CAPNP_LITE

// Calculator
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::AddParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::AddParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::AddParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::AddParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::AddParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::AddResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::AddResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::AddResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::AddResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::AddResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::SubtractParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::SubtractParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::SubtractParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::SubtractParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::SubtractParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::SubtractResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::SubtractResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::SubtractResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::SubtractResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::SubtractResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::MultiplyParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::MultiplyParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::MultiplyParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::MultiplyParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::MultiplyParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::MultiplyResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::MultiplyResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::MultiplyResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::MultiplyResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::MultiplyResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::DivideParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::DivideParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::DivideParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::DivideParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::DivideParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::DivideResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::DivideResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::DivideResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::DivideResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::DivideResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::GetSubCalculatorParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::GetSubCalculatorParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::GetSubCalculatorParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::GetSubCalculatorParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::GetSubCalculatorParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// Calculator::GetSubCalculatorResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Calculator::GetSubCalculatorResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Calculator::GetSubCalculatorResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Calculator::GetSubCalculatorResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Calculator::GetSubCalculatorResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// AddParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t AddParams::_capnpPrivate::dataWordSize;
constexpr uint16_t AddParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind AddParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* AddParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// CalculatorResult
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t CalculatorResult::_capnpPrivate::dataWordSize;
constexpr uint16_t CalculatorResult::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind CalculatorResult::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* CalculatorResult::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE



