name = "Capnp"
uuid = "4a176cb5-e787-4417-92d8-5e07a66a639e"
authors = ["Ondrej Slamecka <ondrej@slamecka.cz>", "Sébastien Celles <s.celles@gmail.com>"]
version = "0.2.0"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.6"